// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYL2Jf29NeYX0iTEytqZGv8hLyZtegPac',
    appId: '1:571641120158:web:cd2a36efe7f0180769c28f',
    messagingSenderId: '571641120158',
    projectId: 'oshaberi-cook',
    authDomain: 'oshaberi-cook.firebaseapp.com',
    storageBucket: 'oshaberi-cook.firebasestorage.app',
    measurementId: 'G-JST2894DGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYugD3MIy_GFjcEiU9m5tig5Ftja3xy-U',
    appId: '1:571641120158:android:c40cd6b6fd774efc69c28f',
    messagingSenderId: '571641120158',
    projectId: 'oshaberi-cook',
    storageBucket: 'oshaberi-cook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLFISPQah0newE-irtneb0KlFIO_VmBTY',
    appId: '1:571641120158:ios:a57ca85d144e6eb369c28f',
    messagingSenderId: '571641120158',
    projectId: 'oshaberi-cook',
    storageBucket: 'oshaberi-cook.firebasestorage.app',
    iosClientId: '571641120158-d64mbm260b7t07nr4or0vtaglm6ila9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.docomohack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLFISPQah0newE-irtneb0KlFIO_VmBTY',
    appId: '1:571641120158:ios:a57ca85d144e6eb369c28f',
    messagingSenderId: '571641120158',
    projectId: 'oshaberi-cook',
    storageBucket: 'oshaberi-cook.firebasestorage.app',
    iosClientId: '571641120158-d64mbm260b7t07nr4or0vtaglm6ila9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.docomohack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYL2Jf29NeYX0iTEytqZGv8hLyZtegPac',
    appId: '1:571641120158:web:25522cdcf4ba559b69c28f',
    messagingSenderId: '571641120158',
    projectId: 'oshaberi-cook',
    authDomain: 'oshaberi-cook.firebaseapp.com',
    storageBucket: 'oshaberi-cook.firebasestorage.app',
    measurementId: 'G-14LY9ET4RN',
  );
}
